INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (1, 'Bench Press', 'An upper-body weight training exercise in which the trainee presses a weight upwards while lying on a weight training bench.', 1, null, 1, 0, 'Wyciskanie na ławce', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (2, 'Shoulder Press', 'Sit up straight on the bench. Grab the barbell and lift off the track. Lowe it to your shoulders.', 1, null, 10, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (21, 'Squat', '', 8, null, 9, 0, 'Przysiad', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (22, 'Incline Dumbell Curl', 'The incline dumbbell curl is a bicep curl variation that placed the lifter in a position that does not allow the shoulder to become involved.', 8, null, 3, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (24, 'Farmer walks', ' This move builds the wrist and finger flexors, as well as engaging just about every other muscle in your body.', 8, null, 7, 0, 'Spacer farmera', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (25, 'Pull-up bar hang', 'This bodyweight exercise helps build not just your wrist and finger flexors, but it’s a great lead-in to tackling scapular pull-ups and other pull-up variations.', 8, null, 7, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (26, 'Russian Twist', 'Start seated on the floor balancing on tailbone with legs bent and elevated so shins are parallel to floor, with ankles crossed, hands clasped at chest and torso leaned back and rotated to left side.', 8, null, 4, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (27, 'Side Plank Dips', 'Start in a left side plank with left forearm on the floor, parallel to top of mat, elbow under shoulder, right hand on hips, and right leg stacked on top of left. Lower hips toward the ground a couple inches, then come back up to start.', 8, null, 4, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (28, 'Hip thrust', 'Lie faceup with knees bent and feet hip-width apart. Place hands on the floor directly under your shoulders, fingers facing away from your body. Squeeze glutes and lift hips into a tabletop position.', 8, null, 8, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (29, 'Glute bridge', 'Lie faceup with knees bent and feet shoulder-width apart. Raise hips straight up off the floor, engaging glutes and bracing core. Lower down slowly, creating your own resistance.', 8, null, 8, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (30, 'Zottman Curl', 'In this movement, you hold a dumbbell in each hand and have a palms-up (supinated) grip on the way up and a palms-down (pronated) grip as you lower the weight, so all of your elbow flexors get hit!', 8, null, 3, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (31, 'Dumbbell Biceps Curl', 'Stand holding a dumbbell in each hand with your arms hanging by your sides. Ensure your elbows are close to your torso and your palms facing forward.', 8, null, 3, 0, 'Uginanie hantli', 'Usiądź na ławce prostej w rozkroku. Weź hantel do ręki, oprzyj łokieć o wewnętrzną część kolana i całkowicie wyprostuj ramię, aby swobodnie zwisało. Drugą rękę oprzyj na przeciwnym kolanie. Zginając łokieć unieś hantel w kierunku barku, następnie wróć do pozycji wyjściowej całkowicie prostując ramię.');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (32, 'Triceps Pushdown', 'The triceps pushdown is an effective single-joint exercise for targeting the triceps. This single-joint movement allows lifters to isolate the muscles while minimizing shoulder involvement and additional joint stress.', 8, null, 2, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (33, 'Skullcrushers', 'The skull crusher is a triceps exercise that can develop the long head of the triceps brachii. This exercise can be done with a bar, cable system, and other free weights.', 8, null, 2, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (34, 'Pull-Up', 'Grab the handles of the pull-up station with your palms facing away from you and your arms fully extended. Your hands should be around shoulder-width apart. Squeeze your shoulder blades together, exhale and drive your elbows towards your hips to bring your chin above the bar. Lower under control back to the start position.', 8, null, 5, 0, 'Podciąganie', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (48, 'Towel pull-up hang', 'Drape two small workout towels, shoulder-width apart, over a pull-up bar. Reach up and grab a towel in each hand with a tight grip. Engage your core and lift your feet off the floor, hanging with your your ankles crossed behind you for as long as you can. Rest and repeat.', 8, null, 10, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (49, 'Kettlebell Swings', 'Place a kettlebell a couple of feet in front of you. Stand with your feet slightly wider than shoulder-width apart and bend your knees to lean forward and grab the handle with both hands. With your back flat, engage your lats to pull the weight between your legs then drive your hips forward and explosively pull the kettlebell up to shoulder height with your arms straight in front of you. Return to the start position and repeat without pauses.', 8, null, 5, 0, '', '');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (61, 'Dumbbell Squat and Press', 'Squat down until the tops of your thighs are parallel to the floor. As you lower, imagine that you’re screwing your feet into the floor by actively pressing your ankles, lower legs, and thighs outward.
Push your body up from the squat as you press the dumbbells directly above your shoulders. Your biceps should be by your ears. Lower the weights and repeat.', 8, null, 4, 2, 'Wyciskanie hantli z przysiadu', 'Stań prosto, trzymając hantle w rękach wyprostowanych po bokach tułowia.
Dociśnij łokcie do korpusu, unieś hantle tak blisko barków, jak to możliwe. Natychmiast zrób przysiad – Twoje uda muszą znaleźć się w pozycji co najmniej równoległej do podłoża.
Wstań i wyciśnij hantle nad głowę. To jedno powtórzenie. Powróć do pozycji startowej i powtórz.');
INSERT INTO app_db.exercise (exercise_id, exercise_name, exercise_info, author, exercise_category, category, exercise_status, exercise_name_pl, exercise_info_pl) VALUES (70, 'test', null, 8, null, 2, 2, '', '');